name: Run lint

on: [pull_request]

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint
        id: lint
        run: |-
          final_message=$(make -s docker_test_lint_gha)
          if [ -z "$final_message" ]; then
          final_message="Thanks for the PR! 🚀<br/>✅Lint checks have passed."
          fi
          final_message="${final_message//'%'/'%25'}"
          final_message="${final_message//$'\n'/'%0A'}"
          final_message="${final_message//$'\r'/'%0D'}"
          echo "$final_message" > log.md
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.pull_request.number }}
          path: ./log.md
